Aardvaark/config/routes.rb
Rails.application.routes.draw do

  root to: 'public#index'
  
  get '/users/profile', to: 'users#profile'

  resource :event, only: [:show]
  resources :relationship_junctions
  resources :event_users

  resources :users do
    resources :events
  end

  resources :organizations do
    resources :events
    resources :users, except: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  post '/organizations/search', to: 'organizations#search'
 
  post 'user_assign', to: 'sessions#user_assign', as: :user_assign
  post 'organization_assign', to: 'sessions#organization_assign', as: :organization_assign
  post 'user_request/:organization_id', to: 'relationship_junctions#user_request', as: :user_request
  
  post 'upgrade/:id', to: 'relationship_junctions#upgrade', as: :upgrade
  post 'downgrade/:id', to: 'relationship_junctions#downgrade', as: :downgrade
  

end

Aardvaark/app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :organization
  has_many :event_users
  has_many :users, through: :event_users
end

Aardvaark/app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    restrict_access
    # @events = Event.all
  end

  def new
    @organization = Organization.find(params[:id])
    @event = @organization.events.build
  end

  def show
    @event_users = EventUser.new

    @event = Event.find(params[:id])
    @organization = Organization.find(@event.organization_id)
    @user = User.find(params[:user_id])
    @users = User.belong_to_org?(@organization)

    @committed_users = User.committed?(@event)
    @available_users = User.available?(@event, @users)

    @upcoming_events = User.upcoming_events(@user)
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      redirect_to organization_path(params[:organization_id])
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])

    if @event.destroy
      redirect_to organization_path(params[:organization_id])
    else
      render organization_path(params[:organization_id])
    end
  end

  protected

  def event_params
    params.require(:event).permit(
      :date, :description, :event_time, :location, :user_id, :organization_id, :type_of_event
      )
  end
end

Aardvaark/app/helpers/events_helper.rb
module EventsHelper
end

Aardvaark/app/views/events/_event_edit_form.html.haml
= form_for @event, url: organization_event_path do |f|
  = f.label "Date" 
  %br
  = f.date_field :date
  %br
  = f.label "Start Time"
  %br
  = f.time_field :event_time
  %br
  = f.label "Location"
  %br
  = f.text_field :location
  %br
  = f.label "Description"
  %br
  = f.text_area :description
  %br
  = f.submit "Submit"

Aardvaark/app/views/events/edit.html.haml
%h1 Editing Event Page
= link_to "Back", organization_path(params[:organization_id])
= render "event_edit_form"

Aardvaark/app/views/events/show.html.haml
#container
  .row
    .col-xs-3
      .row
        .quad-nav.events
      .row
        .quad-nav.org
    .col-xs-6.no-margin
      .advk-logo.text-center
    .col-xs-3
      .row
        .quad-nav.update-profile
      .row
        .quad-nav.logout


  .content-container
    .panel.panel-default
      .panel-heading
        .page-header
          %h1= @organization.name
          %h2
            %small
              = @event.type_of_event
              = " on "
              = @event.date.to_formatted_s(:long_ordinal)
      .panel-body
        %h3
          %strong= "Organizer "
          = User.find(@event.user_id).firstname+" "+User.find(@event.user_id).lastname
        %h3
          %strong= "Location "
          = @event.location
        %h3
          %strong= "Time "
          = @event.event_time.to_s(:time)
        %h3
          %strong= "Notes "
          = @event.description
        %h3
          %strong= "Commitments"
        %table.table
          %th Name
          %th Email
          %th Phone
          %th Gender
          %th Remove
          -@committed_users.each do |user|
            %tr
              %td= User.find(user.user_id).firstname+" "+User.find(user.user_id).lastname
              %td= User.find(user.user_id).email
              %td= User.find(user.user_id).phone
              %td= User.find(user.user_id).gender
              %td= link_to "Remove from event", event_user_path(user.id), method: :delete
        %h3
          Notify volunteers of event details?

    .row
      .col-xs-12
        %p.subheading
          Available Volunteers
        = form_for @event_users do |f|
          -if @available_users != 0
            - @available_users.each do |user|
              -if user.id != @user.id    
                = f.check_box :user_id, {}, User.find(user.id).id, false
                = User.find(user.id).firstname+" "+User.find(user.id).lastname
                = f.hidden_field :event_id, :value => params[:id]
                %br
            = f.submit "Put these jokers to work", class: "btn btn-default"
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
        %input.checkbox#1{:type => "checkbox"}
          %label{:for => 1}
            Test checkbox

        = form_for @event_users do |f|
          -if @event_users.id != @user.id
            = f.collection_check_boxes( :user_id, @users, :id, :firstname )
          = f.submit "Put these jokers to work"
    .row
      .col-xs-12
        %p.subheading
          Available Volunteers
        = form_for @event_users, :html => {:id => "valuesToSubmit"} do |f|
          %select#unassigned-volunteers{:multiple => "multiple"}
            -@available_users.each do |user|
              %option.volunteerAssign{:value => user.id, :data => user.id}
                = User.find(user.id).firstname+" "+User.find(user.id).lastname
            = f.submit "Put these jokers to work", class: "btn btn-default"          
          


    %h1 THIS WILL THE THE MOST AMAZING PAGE IN THE WORLD

    = image_tag "http://i1304.photobucket.com/albums/s540/LenP666/mix/catfish_zps46c073bf.jpg"
        
    #padding-bottom-hack    
    .navbar.navbar-default.navbar-fixed-bottom{role: "navigation"}
      .container-fluid
        = render "users/user_name_check"