Aardvaark/config/routes.rb
Rails.application.routes.draw do

  root to: 'public#index'
  
  get '/users/profile', to: 'users#profile'

  resource :event, only: [:show]
  resources :relationship_junctions
  resources :event_users

  resources :users do
    resources :events
  end

  resources :organizations do
    resources :events
    resources :users, except: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  post '/organizations/search', to: 'organizations#search'
 
  post 'user_assign', to: 'sessions#user_assign', as: :user_assign
  post 'organization_assign', to: 'sessions#organization_assign', as: :organization_assign
  post 'user_request/:organization_id', to: 'relationship_junctions#user_request', as: :user_request
  
  post 'upgrade/:id', to: 'relationship_junctions#upgrade', as: :upgrade
  post 'downgrade/:id', to: 'relationship_junctions#downgrade', as: :downgrade
  

end

Aardvaark/app/models/user.rb
class User < ActiveRecord::Base
  has_many :relationship_junctions
  has_many :organizations, through: :relationship_junctions
  has_many :event_users
  has_many :events, through: :event_users
  has_secure_password

  # validates :firstname, presence: true
  # validates :lastname, presence: true
  validates :email, presence: true
  validates :password, length: { minimum: 2 }, allow_nil: true

  # before_validation(on: :create) do
  #   self.number = number.gsub(/[^0-9]/, "") if attribute_present?("number")
  # end

  # scope :with_vehicle, -> ( vehicle )  do
  #   where(vehicle: true)
  # end

  # scope :are_male, -> ( male ) do
  #   where(gender: male)
  # end

  # scope :are_female, -> (female) do
  #   where(gender: female)
  # end

  # scope :relevant_events, -> (organization) do
    # self.joins(oranizations: organization)
    # OR
    # Event.where(organization: org)
  # end

  def self.search_by_age(min, max)
    self.where("age BETWEEN ? AND ?", min, max)
  end

  def self.upcoming_events(user)
    Event.all.where("user_id = #{user.id}")
  end

  def self.open_events(user)
    user.events
  end

  def self.organizations_not_joined(user)
    # joins('LEFT JOIN relationship_junctions ON users.id = relationship_junctions.user_id').where(:'relationship_junctions.user_id' => nil)
    # joins('LEFT JOIN relationship_junctions ON users.id = relationship_junctions.organization_id')
    # @squirrel_faced_children_that_are_almost_unloveable_because_of_their_disgraceful_genes = RelationshipJunction.joins(:user).where(user_id: user.id)
    # RelationshipJunction.joins(:user).where(user_id: user.id)
    # RelationshipJunction.joins(:user).where("user_id = ? AND role_code = ?", user.id, 0)
    orgs = RelationshipJunction.joins(:user).where("user_id = ?", user.id).select("organization_id")
    Organization.where.not(id: orgs)
  end

  def self.organization_volunteer_pending(user)
    orgs = RelationshipJunction.joins(:user).where("user_id = ? AND role_code = ?", user.id, 0).select("organization_id")
    Organization.where(id: orgs)
  end

  def self.organizations_volunteering_at(user)
    orgs = RelationshipJunction.joins(:user).where("user_id = ? AND role_code != ?", user.id, 0).select("organization_id")
    Organization.where(id: orgs)
  end

  def self.belong_to_org?(org)
    users = RelationshipJunction.joins(:user).where("organization_id = ? AND role_code != ?", org.id, 0).select("user_id")
    User.where(id: users)
  end

  def self.organizer?(user)
    if RelationshipJunction.where("user_id = ? AND role_code = ?", user.id, 2).length == 0
      return false
    else
      return true
    end
  end

  def self.committed?(event)
    EventUser.where("event_id = ?", event.id)
  end

  def self.available?(event, belong_to_org)
    committed = EventUser.where("event_id = ?", event.id).select("user_id")
    belong_to_org.where.not(id: committed)
  end



end

Aardvaark/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    restrict_access
    @users = User.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end


  def show
    restrict_access
    @organizations = Organization.all
    @event = Event.new
    
    @params = params[:id]
    @user = User.find(@params)

    @upcoming_events = User.upcoming_events(@user)
    @open_events = User.open_events(@user)
    @organizations_not_joined = User.organizations_not_joined(@user)
    @organization_volunteer_pending = User.organization_volunteer_pending(@user)
    @organizations_volunteering_at = User.organizations_volunteering_at(@user)
    @organizer = User.organizer?(@user)
  end

  def edit
  end

  def update
  end

  def profile
  end

  def destroy
  end

  def volunteer_request
    # @volunteer_request = (organization: params[:organization_id], user: params[:id], role_code: 0)

    # if @volunteer_request.save
    #   redirect_to root_path, notice: "Request sent to #{organization}! Super duper!"
    # end
  end

protected

  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :phone, :password, :gender, :age, :vehicle, :passenger_capacity )
  end
end

Aardvaark/app/helpers/users_helper.rb
module UsersHelper
    def user_message(current_user)
    add_to_message = ""
    message = "We still need your #{add_to_message}. Please complete your profile."
    case current_user
      when !current_user.firstname
        add_to_message += 'first name' 
      when !current_user.lastname
        add_to_message += 'last name'
      when !current_user.email
        add_to_message += 'email'
      when !current_user.phone
        add_to_message += 'phone number'
      when !current_user.gender
        add_to_message += 'gender'
      when !current_user.skills
        add_to_message += 'skills'
      when !current_user.age
        add_to_message += 'age'
      when !current_user.vehicle
        add_to_message += 'vehicle'
      when !current_user.passenger_capacity
        add_to_message += 'passenger capacity'
      else
        message = "Welcome back, #{current_user.firstname}"
        return message
      end
    return "Hi #{current_user.firstname}. #{message}"
  end

  # def relevant_events
  #   events_array = []
  #   @organizations = Organization.all
  #   @organizations.each do |organization| 
  #   events_array << organization.events.where(current_user[:id] == organization.events_users_tables.user_id)
  #   end
  #   events.flatten
  # end
end

Aardvaark/app/views/users/_user_create_an_event.html.haml
.row
  .col-xs-12
    %p.subheading
      CREATE AN EVENT
    = form_for ([@user, @event]) do |f|
      .input-group.margin-bottom-sm
        %span.input-group-addon
          %i.fa.fa-rocket.fa-fw
        = f.select :type_of_event, ["Street Hit"], {}, { :class => "form-control" }
      .input-group.margin-bottom-sm
        %span.input-group-addon
          %i.fa.fa-sitemap.fa-fw
        = f.collection_select :organization_id, @organizations_volunteering_at.all, :id, :name, {:prompt => "Who you doing this for?"}, { :class => "form-control" }
      .input-group.margin-bottom-sm
        %span.input-group-addon
          %i.fa.fa-user.fa-fw
        = f.collection_select :user_id, [current_user], :id, :firstname, {}, { :class => "form-control" }
      .input-group.margin-bottom-sm
        %span.input-group-addon
          %i.fa.fa-calendar.fa-fw
        = f.date_field :date, class: "form-control"
      .input-group.margin-bottom-sm
        %span.input-group-addon
          %i.fa.fa-clock-o.fa-fw
        = f.time_field :event_time, class: "form-control"
      .input-group.margin-bottom-sm
        %span.input-group-addon
          %i.fa.fa-location-arrow.fa-fw
        = f.text_field :location, class: "form-control", placeholder: "location"
      .input-group.margin-bottom-sm
        %span.input-group-addon
          %i.fa.fa-quote-left.fa-fw
        = f.text_area :description, class: "form-control"
      %span.input-group-btn
        = f.submit "Submit", class: "btn btn-default"
%br

Aardvaark/app/views/users/_user_name_check.html.haml
- if !current_user.nil?
  - if current_user.try(:firstname)
    %h2 
      #{current_user.firstname} #{current_user.lastname}
    %p.navbar-text.navbar-right= link_to "LOG OUT", session_path("current_user"), method: :delete
  - else
    %h1.text-center Hey, hey #{current_user.name}, get out!

Aardvaark/app/views/users/_user_organization_status.html.haml
.row
  .col-xs-12
    %p.subheading
      ORGANIZATIONS
    .panel.panel-primary
      .panel-heading
        .panel-title
          You're Volunteering With These Guys
      .panel-body
        - @organizations_volunteering_at.each do |org|
          %p= Organization.find(org.id).name

    .panel.panel-info
      .panel-heading
        .panel-title
          Pending approval
      .panel-body
        - @organization_volunteer_pending.each do |org|
          %p= Organization.find(org.id).name

    .panel.panel-warning
      .panel-heading
        .panel-title
          Available Organizations
      .panel-body
        - @organizations_not_joined.each do |org|
          %p= Organization.find(org.id).name
          = link_to "Wanna join?", user_request_path(org.id), method: :post

Aardvaark/app/views/users/_user_upcoming_events.html.haml
.row
  .col-xs-12
    %p.subheading
      YOUR EVENTS
    - if @upcoming_events.length == 0
      %p= "No events! Get involved, you slacker!"
    - else
      .list-group
        - @upcoming_events.each do |event|
          = link_to user_event_path(current_user.id, :id => event.id), :class => "list-group-item" do
            %h4.list-group-item-heading 
              = event.type_of_event
              %strong
                %small= event.date.to_s
            %h3= Organization.find(event.organization_id).name
            %p.list-group-item-text
              %strong= "Organizer "
              = User.find(event.user_id).firstname+" "+User.find(event.user_id).lastname
            %p.list-group-item-text
              %strong= "Location "
              = event.location
            %p.list-group-item-text
              %strong= "Time "
              = event.event_time.to_s(:time)
            %p.list-group-item-text
              %strong= "Notes "
              = event.description

Aardvaark/app/views/users/edit.html.haml
%h1 Edit your stuffs

= form_for @user do |f|
  = f.text_field :email, placeholder: "you@email.com"
  %br
  = f.password_field :password, placeholder: "password"
  %br
  = f.text_field :firstname, placeholder: "first name"
  %br
  = f.text_field :lastname, placeholder: "last name"
  %br
  = f.text_field :phone, placeholder: "phone number"
  %br
  = f.submit "Update"

Aardvaark/app/views/users/index.html.haml
%h1 users index

/ signup form for users
%h3 User sign up

= form_for @users do |f|

  = f.label "first name"
  = f.text_field :firstname
  %br
  = f.label "last name"
  = f.text_field :lastname
  %br
  = f.label "email"
  = f.text_field :email
  %br
  = f.label "phone number"
  = f.text_field :phone
  %br
  = f.label "gender"
  = select_tag "gender", "<option>female</option><option>male</option><option>-</option>".html_safe
  %br
  = f.label "age"
  = f.number_field :age
  %br
  = f.label "Do you have a vehicle?"
  = select_tag "vehicle", "<option>yes</option><option>no</option>".html_safe
  %br
  = f.label "how many passengers can your vehicle take?"
  = f.number_field :passenger_capacity
  %br
  = f.label "password"
  = f.password_field :password
  %br
  = f.submit "Submit"
  %br

%h2 Log In

= form_tag session_path do

  = label_tag "email"
  = text_field_tag "email"
  %br
  = label_tag :password
  = password_field_tag :password
  %br
  = submit_tag "Submit"

- if !current_user.nil?
  - if current_user.try(:firstname)
    %h3.text-center Hey, hey #{current_user.firstname}, you're a volunteer!
    = link_to "Log Out", session_path("current_user"), method: :delete
  - else
    %h3.text-center Hey, hey #{current_user.name}, you so'n so, get outta here you Organization!
    = link_to "Log Out", session_path("current_user"), method: :delete

Aardvaark/app/views/users/profile.html.haml
%h1 user profile page

%dl
  %dt Pic
  %dd showing your cuteness and loveability
  %dt My events
  %dd what you've signed up for 
  %dd deets(where/when/who/how)
  %dt Upcoming Events
  %dd a board of events you can choose to join. Maybe they are starred if they've been filtered-meaning you are expecially useful for them!
  %dt Past Events
  %dd A record of past involvement and attendance(visible as a reliability rating or no?)

  / = p relevant_events

  / = p current_user.firstname 

  = p user_message(current_user)

Aardvaark/app/views/users/show.html.haml
#container
  .row
    .col-xs-3
      .row
        .quad-nav.events
      .row
        .quad-nav.org
    .col-xs-6.no-margin
      .advk-logo.text-center
    .col-xs-3
      .row
        .quad-nav.update-profile
      .row
        .quad-nav.logout

  .content-container
    
    = render "user_upcoming_events"
    
    .row
      .col-xs-12
        %p.subheading
          UPCOMING EVENTS
        - if @open_events.length == 0
          %p= "Nothing important's happening in your life."
        - else
          .list-group
            - @open_events.each do |event|
              = link_to user_event_path(current_user.id, :id => event.id), :class => "list-group-item" do
                %h4.list-group-item-heading
                  WALKATHON
                  %strong
                    %small= event.date.to_s
                %h3= event.organization_id
                %p.list-group-item-text
                  = event.description
    
    -if @organizer == true
      = render "user_create_an_event"

    = render "user_organization_status"

    #padding-bottom-hack    
    .navbar.navbar-default.navbar-fixed-bottom{role: "navigation"}
      .container-fluid
        = render "user_name_check"

Aardvaark/app/views/users/testhotnessofpage.html.haml
#hero-div
  #container-fluid
    .row
      .col-md-6.text-center
        .form-div

          %h3 User sign up

          = form_tag users_testhotnessofpage_path do
            .form-group
            %i.fa.fa-heart-o.fa-fw
            = label_tag "first name"
            = text_field_tag :firstname
            .form-group
            %i.fa.fa-heart.fa-fw
            = label_tag "last name"
            = text_field_tag :lastname
            %br
            %div.form-group
            .input-group.margin-bottom-sm
            %i.fa.fa-envelope-o.fa-fw
            = label_tag "email"
            = text_field_tag :email
            %br
            %div.form-group
            .input-group.margin-bottom-sm
            %i.fa.fa-phone.fa-fw
            = label_tag "phone number"
            = text_field_tag :phone
            %br
            %div.form-group
            .input-group.margin-bottom-sm
            %i.fa.fa-stethoscope.fa-fw
            = label_tag "gender"
            = select_tag "gender", "<option>female</option><option>male</option><option>-</option>".html_safe
            %br
            %div.form-group
            .input-group.margin-bottom-sm
            %i.fa.fa-wheelchair.fa-fw
            = label_tag "age"
            = text_field_tag :age
            %br
            %div.form-group
            .input-group.margin-bottom-sm
            %i.fa.fa-truck.fa-fw
            = label_tag "Do you have a vehicle?"
            = select_tag "vehicle", "<option>yes</option><option>no</option>".html_safe
            %br
            %div.form-group
            .input-group.margin-bottom-sm
            %i.fa.fa-thumbs-up.fa-fw
            = label_tag "how many passengers can your vehicle take?"
            = text_field_tag :passenger_capacity
            %br
            %div.form-group
            .input-group.margin-bottom-sm
            %i.fa.fa-key.fa-fw
            = label_tag "password"
            = text_field_tag :password
            %br
            = submit_tag "Submit"
            %br

      .col-md-6.text-center
        .form-div2
          .row
            .col-md-12
              .half-way-house-of-vertical-lifestyles
                %h3 Log In

                = form_tag session_path do
                  .input-group.margin-bottom-sm
                  %i.fa.fa-envelope-o.fa-fw
                  = label_tag "email"
                  = text_field_tag "email"
                  %br
                  .input-group.margin-bottom-sm
                  %i.fa.fa-key.fa-fw
                  = label_tag :password
                  = password_field_tag :password
                  = submit_tag "Submit"
                
                %hr.biggah

              .half-way-house-of-vertical-lifestyles
                %h3= "logout, #{'you'}"
                = form_tag session_path do
                  = submit_tag "Logout"