Aardvaark/config/routes.rb
Rails.application.routes.draw do

  root to: 'public#index'
  
  get '/users/profile', to: 'users#profile'

  resource :event, only: [:show]
  resources :relationship_junctions
  resources :event_users

  resources :users do
    resources :events
  end

  resources :organizations do
    resources :events
    resources :users, except: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  post '/organizations/search', to: 'organizations#search'
 
  post 'user_assign', to: 'sessions#user_assign', as: :user_assign
  post 'organization_assign', to: 'sessions#organization_assign', as: :organization_assign
  post 'user_request/:organization_id', to: 'relationship_junctions#user_request', as: :user_request
  
  post 'upgrade/:id', to: 'relationship_junctions#upgrade', as: :upgrade
  post 'downgrade/:id', to: 'relationship_junctions#downgrade', as: :downgrade
  

end

Aardvaark/app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :relationship_junctions
  has_many :events
  has_many :users, through: :relationship_junctions
  has_secure_password
  
  validates :name, presence: true
  validates :email, presence: true

  # before_validation(on: :create) do
  #   self.number = number.gsub(/[^0-9]/, "") if attribute_present?("number")
  # end  

  def self.find_requests(org)
    org.users.where("role_code = 0")
  end

  def self.find_volunteers(org)
    org.users.where("role_code = 1")
  end

  def self.find_volunteer_supers(org)
    org.users.where("role_code = 2")
  end

end

Aardvaark/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    restrict_access
    @organizations = Organization.all
    @organization = Organization.new
    @users = User.all
    @events = Event.all
    @event = Event.new

    # if params[:age]
    #   query_params = params[:age].split("-")
    #   min = query_params[0].strip.to_i
    #   max = query_params[1].strip.to_i
    #   @users = @users.search_by_age(min, max)
    # end
  end

  def show
    restrict_access
    @event = Event.new
    @organization = Organization.find(params[:id]) 
    @invites = Organization.find_requests(@organization)
    @volunteers = Organization.find_volunteers(@organization)
    @volunteer_supers = Organization.find_volunteer_supers(@organization)
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)

      if @organization.save
        session[:organization_id] = @organization.id
        redirect_to root_path, notice: "Hello, #{@organization.name}!"
      else
        render :new
      end
  end


  def edit
  end

  def search
    # @users = Organization.users.all
    # @users = @users.with_vehicle(params[:vehicle]) if params[:vehicle].present?
    # @users = @users.are_female(params[:gender]) if params[:gender].present?
    # @users = @users.are_male(params[:gender]) if params[:gender].present?
  end

  def update
  end

  def destroy
  end
  
  protected

  def organization_params
    params.require(:organization).permit(:name, :email, :representative_name, :password)
  end
end

Aardvaark/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

Aardvaark/app/views/organizations/index.html.erb
<h1>Organization index</h1>

<dl>
<dt>dashboard</dt>
<dt>create a new event</dt>
  <dd>form (deets)</dd>
  <dd>add volunteers to email(filters)</dd>
  <dd>update events board</dd>
<dt>update an event</dt>
  <dd>send email, update events board</dd>
<dt>cancel an event</dt>
  <dd>send email, update events board</dd>
</dl>

Aardvaark/app/views/organizations/index.html.haml
#container
  %h1.text-center organizations index
  - if !current_user.nil?
    - if current_user.try(:firstname)
      %h3.text-center Hey, hey #{current_user.firstname}, you're a volunteer and shouldn't be here!
      %h3.text-center= link_to "Log Out", session_path("current_user"), method: :delete
    - else
      %h3.text-center Hey, hey #{current_user.name}, you so'n so, Organization, you
      %h3.text-center= link_to "Log Out", session_path("current_user"), method: :delete
  

  .row
    .col-xs-4.col-md-4
    .col-xs-4.col-md-4.text-center
      %h3 Registered organizations
      - @organizations.each do |org|
        = org.name
        = link_to "GO THIS PAGE, PEON!", organization_path(org)
        %br
    .col-xs-4.col-md-4
  
  .row
    .col-xs-4.col-md-4
    .col-xs-4.col-md-4.text-center
      %h3 Registered events
      - @events.each do |event|
        %h4= event.description
        = event.location+" / "+event.date.to_s+" / "+event.organization_id.to_s
        = link_to "GO THIS PAGE, PEON!", event_path(event)
        %br
    .col-xs-4.col-md-4

  .row
    .col-xs-4.col-md-4
    .col-xs-4.col-md-4.text-center
      %h3 Organization sign up
      = form_for @organization do |f|
        = f.text_field :name, placeholder: "name of organization"
        %br
        = f.text_field :representative_name, placeholder: "name of representative"
        %br
        = f.text_field :email, placeholder: "email"
        %br
        = f.password_field :password, placeholder: "password"
        %br
        = f.submit "Submit"
        %br    
    .col-xs-4.col-md-4



/ %h2 filter volunteers

/ = form_tag organizations_search_path do 

/   = label_tag "search by vehicle"
/   = text_field_tag :vehicle
/   %br
/   = label_tag "search by gender"
/   = text_field_tag :gender
/   %br
/   = label_tag "search by age"
/   = select_tag "age", "<option>18 -25</option><option>26 - 45</option><option>46 + </option>".html_safe
/   = submit_tag("search")

Aardvaark/app/views/organizations/search.html.haml
- @users.each do |user|
  - name = user.firstname
  %p #{name}

  

Aardvaark/app/views/organizations/show.html.haml
#container
  - if !current_user.nil?
    - if current_user.try(:firstname)
      %h1.text-center Hey, hey #{current_user.firstname}, you're a volunteer and shouldn't be here!
      %h3.text-center= link_to "Log Out", session_path("current_user"), method: :delete
    - else
      %h1.text-center Hey, hey #{current_user.name}, you so'n so, Organization, you
      %h3.text-center= link_to "Log Out", session_path("current_user"), method: :delete

  .row
    .col-xs-4.col-md-4
    .col-xs-4.col-md-4.text-center
      %h2= "Your Volunteer Requests" 
      - @invites.each do |invite|
        - request = RelationshipJunction.find_by("user_id = #{invite.id} AND organization_id = #{@organization.id}")
        %h4= invite.firstname+" "+invite.lastname
        = link_to "Welcome aboard, sailor?", relationship_junction_path(request.id), method: :patch
        = link_to "Deny", relationship_junction_path(request.id), method: :delete
        %br
    .col-xs-4.col-md-4

  .row
    .col-xs-4.col-md-4
    .col-xs-4.col-md-4.text-center
      %h2= "Your Volunteers" 
      - @volunteers.each do |volunteer|
        - request = RelationshipJunction.find_by("user_id = #{volunteer.id} AND organization_id = #{@organization.id}")
        %h4= volunteer.firstname+" "+volunteer.lastname
        = link_to "Able to organize?", upgrade_path(request.id), method: :post
        = link_to "Revoke privilages?", downgrade_path(request.id), method: :post
        = link_to "Delete", relationship_junction_path(request.id), method: :delete
        %br
    .col-xs-4.col-md-4

  .row
    .col-xs-4.col-md-4
    .col-xs-4.col-md-4.text-center
      %h2= "Your Organizing Volunteers" 
      - @volunteer_supers.each do |volunteer|
        - request = RelationshipJunction.find_by("user_id = #{volunteer.id} AND organization_id = #{@organization.id}")
        %h4= volunteer.firstname+" "+volunteer.lastname
        = link_to "Revoke privilages?", downgrade_path(request.id), method: :post
        = link_to "Delete", relationship_junction_path(request.id), method: :delete
        %br
    .col-xs-4.col-md-4

  .row
    .col-xs-4.col-md-4
    .col-xs-4.col-md-4.text-center
      %h2= @organization.name+"'s Events" 
      - @organization.events.each do |event|
        %h4= event.description
        = link_to "Delete?", organization_event_path(current_user, event.id), method: :delete, confirm: "You sure?"
        = link_to "Modify?", edit_organization_event_path(current_user, event.id)
        %br
    .col-xs-4.col-md-4

  .row
    .col-xs-4.col-md-4
    .col-xs-4.col-md-4.text-center
      %h2 Create an event    
      = form_for ([@organization, @event]) do |f|
        =f.label "point person"
        %br
        = f.collection_select :user_id, @volunteer_supers.all, :id, :firstname
        %br
        = f.label "date"
        %br
        = f.date_field :date
        %br
        = f.label "event time"
        %br
        = f.time_field :event_time
        %br
        = f.label "location"
        %br
        = f.text_field :location
        %br
        = f.label "description"
        %br
        = f.text_area :description
        %br
        = f.submit "Submit"
        %br
    .col-xs-4.col-md-4    



/ - if current_user
/   %h3= "logout, #{current_user.firstname}"
/   = button_to "Logout", session_path, method: :delete

/ %h2 list of volunteers

/ - @users.each do |user|
/   - volunteer = user.firstname
/   %p #{volunteer}

/ %h2 filter volunteers

/ = form_tag organizations_search_path do 

/   = label_tag "search by vehicle"
/   = text_field_tag :vehicle
/   %br
/   = label_tag "search by gender"
/   = text_field_tag :gender
/   %br
/   = label_tag "search by age"
/   = select_tag "age", "<option>18 -25</option><option>26 - 45</option><option>46 + </option>".html_safe
/   = submit_tag("search")